Repository wakamorekun/janken_2, pull requests merged in 2024-11, with the labels that each got.

#5 player.py作成_#1
  source/computer.py
  source/player.py
  tests/test_player.py
Labels: 優先1

#6 janken_judge_#4
  source/janken_judge.py
Labels: 優先3

#7 janken.py_#3
  source/janken.py
Labels: 優先2
